export * from './Welcome/Welcome';
export * from './AboutMe/AboutMe';
export * from './MyResume/MyResume';
export * from './MyProjects/MyProjects';
export * from './Pricing/Pricing';
export * from './MyBlog/MyBlog';
export * from './MyClients/MyClients';
export * from './Contact/Contact';
export * from './Map/Map';