import Head from 'next/head';
import React from 'react';
import { Htag, Button } from '../components';
import styles from '../styles/Home.module.css';

export default function Home(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Htag tag="h5">Full time</Htag>
        <Button appearance="ghost" size="middle">View Resume</Button>
      </main>
    </div>
  );
}
